spring:
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect